package dev.bozlak.followcurrentinventorydifference.business.abstracts;

import dev.bozlak.followcurrentinventorydifference.entitiesanddtos.events.EventProductIdEventAmountAndDate;

public interface EventAffectingInventoryService {
    boolean addEventAffectingInventory(EventProductIdEventAmountAndDate eventProductIdEventAmountAndDate);
}
